name: Deploy Backend with Docker

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set Up SSH Key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to Fasthosts
        run: |
          ssh -o StrictHostKeyChecking=no root@87.106.67.244 << 'EOF'
            cd Taskify
            git pull origin main

            # Stop and remove old containers
            docker-compose down

            # Rebuild and start new containers
            docker-compose up -d --build

            # Cleanup unused Docker images
            docker system prune -af
          EOF
